# Generated by Django 4.0 on 2022-01-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='context',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
