# Generated by Django 4.0 on 2022-01-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dialogue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
