# Generated by Django 4.0 on 2022-01-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dialogue_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='trigger',
            field=models.CharField(default='click', max_length=30),
        ),
    ]
